version: "3.9"
services:
  dreamscape_front:
    build: ./dreamscape_front
    container_name: dreamscape_front
    working_dir: /dreamscape_front
    ports:
      - "8081:8080"
    command: serve -s dist -l 8080
    restart: unless-stopped

  dreamscape_front2:
    build: ./dreamscape_front
    container_name: dreamscape_front2
    working_dir: /dreamscape_front
    ports:
      - "8000:8080"
    command: serve -s dist -l 8080
    restart: unless-stopped

  dreamscape_back:
    build: ./dreamscape_back
    container_name: dreamscape_back
    working_dir: /dreamscape_back
    ports:
      - "3001:3000"
    environment:
      MONGODB_CONNSTRING: mongodb://${DB_USER}:${DB_PWD}@mongodb
    command: node dist/main
    restart: unless-stopped
    links:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: mongo_ds
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PWD}
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
      - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    restart: unless-stopped