version: "3.9"
services:
  dreamscape_front:
    build:
      context: ./dreamscape_front
      args:
        SERVER_ADDRESS: http://${SERVER_HOST}:${SERVER_PORT}
    container_name: dreamscape_front_${FRONT_PORT}
    working_dir: /dreamscape_front
    ports:
      - "${FRONT_PORT}:8080"
    command: serve -s dist -l 8080
    restart: unless-stopped

  dreamscape_back:
    build: ./dreamscape_back
    container_name: dreamscape_back_${SERVER_PORT}
    working_dir: /dreamscape_back
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      MONGODB_CONNSTRING: mongodb://${DB_USER}:${DB_PWD}@mongodb
    command: node dist/main
    restart: unless-stopped
    links:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: mongo_ds_${DB_PORT}
    environment:
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      INIT_DB: ${INIT_DB}
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PWD}
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - ./data:/data/db
      - ./init-mongodb:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped