version: "3.9"
services:
  dreamscape_front:
    build: ./dreamscape_front
    container_name: dreamscape_front
    working_dir: /dreamscape_front
    ports:
      - "8081:8080"
    environment:
      MONGODB_CONNSTRING: mongodb://${DB_USER}:${DB_PASS}@mongodb
    command: serve -s dist -l 8080
    restart: unless-stopped

  dreamscape_front2:
    build: ./dreamscape_front
    container_name: dreamscape_front2
    working_dir: /dreamscape_front
    ports:
      - "8000:8080"
    environment:
      MONGODB_CONNSTRING: mongodb://${DB_USER}:${DB_PASS}@mongodb
    command: serve -s dist -l 8080
    restart: unless-stopped
    links:
      - mongodb

  dreamscape_back:
    build: ./dreamscape_back
    container_name: dreamscape_back
    working_dir: /dreamscape_back
    ports:
      - "3001:3000"
    command: node dist/main
    restart: unless-stopped

  mongodb:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    restart: unless-stopped